development:
  adapter:  mysql2
  database: bbg_development
  username: root
  password:
  pool: 5
  timeout: 5000
  encoding: utf8
test:
  adapter:  mysql2
  database: bbg_test
  username: root
  password:
  pool: 5
  timeout: 5000
  encoding: utf8

# production:
#   adapter:  mysql2
#   database: bbg_production
#   username: root
#   password:
#   pool: 5
#   timeout: 5000
#   encoding: utf8
